# Generated by Django 2.1.5 on 2019-02-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190219_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='acc_amount',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
