# Generated by Django 2.1.5 on 2019-02-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190221_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='acc_amount',
            field=models.IntegerField(default=1000),
        ),
    ]
