# Generated by Django 2.1.5 on 2019-04-25 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190416_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code_payment',
            name='updated',
        ),
    ]
