# Generated by Django 2.1.5 on 2019-04-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_code_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code_payment',
            name='amount',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='code_payment',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
