# Generated by Django 2.0.7 on 2018-12-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cover_image',
            field=models.FileField(upload_to=''),
        ),
    ]
