# Generated by Django 2.0.7 on 2019-01-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20190104_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
