# Generated by Django 2.0.7 on 2019-01-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_movie_movie_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_slug',
            new_name='slug',
        ),
    ]
