# Generated by Django 2.0.7 on 2019-01-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20190110_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='translated',
            field=models.BooleanField(default=False),
        ),
    ]
