# Generated by Django 2.0.7 on 2019-01-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20190111_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Series'),
        ),
    ]
