# Generated by Django 2.0.7 on 2019-01-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_auto_20190111_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='seriegenre', to='movie.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='moviegenre', to='movie.Genre'),
        ),
    ]
