# Generated by Django 2.0.7 on 2019-01-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_episode_episodenumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['season', 'episodenumber'], 'verbose_name_plural': 'Episodes'},
        ),
        migrations.AddField(
            model_name='movie',
            name='theme',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
    ]
