# Generated by Django 2.0.7 on 2019-01-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_auto_20190124_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
    ]
