# Generated by Django 2.0.7 on 2019-01-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0017_auto_20190124_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='moviegenre', to='movie.Genre'),
        ),
    ]
