# Generated by Django 2.1.5 on 2019-01-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0018_auto_20190124_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cover_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
