# Generated by Django 2.1.5 on 2019-02-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0026_auto_20190214_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='app',
            field=models.FileField(blank=True, null=True, upload_to='./media/app'),
        ),
    ]
