# Generated by Django 2.1.5 on 2019-02-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0027_site_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='story_line',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
