# Generated by Django 2.1.5 on 2019-03-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0028_movie_story_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episodenumber',
            field=models.CharField(blank=True, choices=[('E01', 'Episode 1'), ('E02', 'Episode 2'), ('E03', 'Episode 3'), ('E04', 'Episode 4'), ('E05', 'Episode 5'), ('E06', 'Episode 6'), ('E07', 'Episode 7'), ('E08', 'Episode 8'), ('E09', 'Episode 9'), ('E10', 'Episode 10'), ('E11', 'Episode 11'), ('E12', 'Episode 12'), ('E13', 'Episode 13'), ('E14', 'Episode 14'), ('E15', 'Episode 15')], max_length=112, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.CharField(blank=True, choices=[('S01', 'Season 1'), ('S02', 'Season 2'), ('S03', 'Season 3'), ('S04', 'Season 4'), ('S05', 'Season 5'), ('S06', 'Season 6')], max_length=112, null=True),
        ),
    ]
