# Generated by Django 2.1.5 on 2019-03-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0029_auto_20190301_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='story_line',
            field=models.CharField(blank=True, max_length=222, null=True),
        ),
    ]
