# Generated by Django 2.1.5 on 2019-03-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0032_serie_genre_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='tags',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre_choices',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
    ]
