# Generated by Django 2.1.5 on 2019-03-02 19:00

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('movie', '0033_auto_20190302_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre_choices',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='genre_choices',
        ),
        migrations.AddField(
            model_name='movie',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='serie',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
