# Generated by Django 2.1.5 on 2019-03-04 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0034_auto_20190302_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasoname', models.CharField(blank=True, choices=[('S01', 'Season 1'), ('S02', 'Season 2'), ('S03', 'Season 3'), ('S04', 'Season 4'), ('S05', 'Season 5'), ('S06', 'Season 6')], max_length=122, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='episode',
            old_name='file',
            new_name='video_file',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='title',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='video',
        ),
        migrations.AddField(
            model_name='episode',
            name='story',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Season'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='name',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.Serie'),
        ),
    ]
