# Generated by Django 2.1.5 on 2019-03-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0036_auto_20190306_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='episode_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='movie_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
