# Generated by Django 2.1.5 on 2019-03-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0038_downloaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloaded',
            name='movie',
            field=models.ManyToManyField(blank=True, related_name='my_movies', to='movie.Movie'),
        ),
    ]
