# Generated by Django 2.1.5 on 2019-04-16 19:48

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0039_auto_20190325_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='thumnail'),
        ),
    ]
