# Generated by Django 2.1.5 on 2019-04-16 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0040_movie_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='thumbnail',
        ),
    ]
