# Generated by Django 2.1.5 on 2019-04-25 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0042_codecreate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeCreate',
        ),
    ]
